/// Flutter icons MyFlutterApp
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Fontelico, Copyright (C) 2012 by Fontello project
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://fontello.com
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Maki, Copyright (C) Mapbox, LCC
///         Author:    Mapbox
///         License:   BSD (https://github.com/mapbox/maki/blob/gh-pages/LICENSE.txt)
///         Homepage:  http://mapbox.com/maki/
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static const IconData unmotivated = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData motivated = IconData(0xf501, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData yes = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData no = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData indifferent = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData distracted = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData happy = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angry = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sad = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData anxious = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gastro = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData energy = IconData(0xe914, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tired = IconData(0xe915, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData control = IconData(0xe99e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exhausted = IconData(0xea6a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ache = IconData(0xea6c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fully = IconData(0xea6e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ok = IconData(0xea6f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forget = IconData(0xf128, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calm = IconData(0xf209, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stress = IconData(0xf579, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData excited = IconData(0xf59a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mood = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
